defaults: &defaults
  DROPBOX_ACCESS_TOKEN: <%= ENV['ACCESS_TOKEN'] %>
  SLACK_INCOMING_WEBHOOK_URL: <%= ENV['SLACK_INCOMING_WEBHOOK_URL'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults